# Generated by Django 5.1.6 on 2025-04-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=255)),
                ('User_or_Agent', models.BooleanField(default=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_number', models.IntegerField()),
                ('Password', models.CharField(max_length=8)),
                ('Referral_code', models.CharField(max_length=255)),
            ],
        ),
    ]
