# Generated by Django 5.1.6 on 2025-04-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_users',
            name='Referral_code',
        ),
    ]
