# Generated by Django 5.1.6 on 2025-04-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_API', '0002_remove_application_users_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_users',
            name='Referral_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
