# Generated by Django 5.1.6 on 2025-04-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search_Places_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_places',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search_places',
            name='bus_operator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='search_places',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search_places',
            name='on_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search_places',
            name='seat_prices',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
