# Generated by Django 5.1.6 on 2025-04-28 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search_Places_API', '0002_alter_search_places_arrival_time_and_more'),
        ('cities_API', '0002_place_delete_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_places',
            name='from_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_places', to='cities_API.place'),
        ),
        migrations.AlterField(
            model_name='search_places',
            name='to_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_places', to='cities_API.place'),
        ),
    ]
