# Generated by Django 5.1.6 on 2025-04-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search_Places_API', '0003_alter_search_places_from_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_places',
            name='from_place',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='search_places',
            name='to_place',
            field=models.CharField(max_length=255),
        ),
    ]
