# Generated by Django 5.1.6 on 2025-04-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search_Places_API', '0006_alter_search_places_from_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_place', models.CharField(max_length=255)),
                ('to_place', models.CharField(max_length=255)),
                ('on_date', models.DateField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('bus_operator', models.CharField(blank=True, max_length=255, null=True)),
                ('seat_prices', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='search_places',
        ),
    ]
