# Generated by Django 5.1.6 on 2025-04-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search_Places_API', '0008_search_bus_trips_remove_search_bus_from_place_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='search_bus',
        ),
    ]
