# Generated by Django 5.1.6 on 2025-04-29 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search_Places_API', '0009_delete_search_bus'),
        ('cities_API', '0002_place_delete_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_bus_trips',
            name='from_place',
        ),
        migrations.RemoveField(
            model_name='search_bus_trips',
            name='to_place',
        ),
        migrations.AddField(
            model_name='search_bus_trips',
            name='from_place_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_place_id', to='cities_API.place'),
        ),
        migrations.AddField(
            model_name='search_bus_trips',
            name='to_place_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_place_id', to='cities_API.place'),
        ),
    ]
