# Generated by Django 5.1.6 on 2025-04-29 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search_Places_API', '0012_alter_search_bus_trips_from_place_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_bus_trips',
            name='on_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
