# Generated by Django 5.1.6 on 2025-04-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search_Places_API', '0013_alter_search_bus_trips_on_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_bus_trips',
            name='from_place_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='search_bus_trips',
            name='to_place_id',
            field=models.CharField(max_length=255),
        ),
    ]
