# Generated by Django 5.1.6 on 2025-04-29 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search_Places_API', '0014_alter_search_bus_trips_from_place_id_and_more'),
        ('cities_API', '0002_place_delete_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_bus_trips',
            name='from_place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_place_id', to='cities_API.place'),
        ),
        migrations.AlterField(
            model_name='search_bus_trips',
            name='to_place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_place_id', to='cities_API.place'),
        ),
    ]
