# Generated by Django 5.1.6 on 2025-03-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login_details',
            options={},
        ),
        migrations.RemoveField(
            model_name='login_details',
            name='created',
        ),
    ]
