# Generated by Django 5.1.6 on 2025-03-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_themeconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThemeConfiguration',
        ),
    ]
