# Generated by Django 5.1.6 on 2025-04-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
