# Generated by Django 5.1.6 on 2025-03-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_posttranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
