# Generated by Django 5.1.6 on 2025-04-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logged_in_Users',
            new_name='Login_Users',
        ),
    ]
