# Generated by Django 5.1.6 on 2025-04-15 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_API', '0002_rename_logged_in_users_login_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login_Users',
        ),
    ]
