# Generated by Django 5.1.6 on 2025-04-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_API', '0003_delete_login_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_number', models.IntegerField()),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
    ]
