# Generated by Django 5.1.6 on 2025-04-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cities', models.CharField(max_length=255)),
                ('states', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='places',
        ),
    ]
